# ロジスティック回帰モデルの作成

## 関連するライブラリのインポート

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
%matplotlib inline

## データの読み込み

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason4  Month Value  Date of the Week  \
0         0         0         0        1            7                 1   
1         0         0         0        0            7                 1   
2         0         0         0        1            7                 2   
3         1         0         0        0            7                 3   
4         0         0         0        1            7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## ターゲットの作成

In [6]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [14]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median() , 1, 0)

In [15]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [16]:
data_preprocessed['Excessive Absenteeism'] = targets

In [17]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason4  Month Value  Date of the Week  \
0         0         0         0        1            7                 1   
1         0         0         0        0            7                 1   
2         0         0         0        1            7                 2   
3         1         0         0        0            7                 3   
4         0         0         0        1            7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [18]:
## 不要なデータ列の削除

data_with_targets = data_preprocessed.drop('Absenteeism Time in Hours', axis=1)

In [20]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason4  Month Value  Date of the Week  \
0         0         0         0        1            7                 1   
1         0         0         0        0            7                 1   
2         0         0         0        1            7                 2   
3         1         0         0        0            7                 3   
4         0         0         0        1            7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

## 入力データの管理

In [22]:
data_with_targets.shape

(700, 15)

In [26]:
data_with_targets.iloc[:, :14]

Reason_1  Reason_2  Reason_3  Reason4  Month Value  Date of the Week  \
0           0         0         0        1            7                 1   
1           0         0         0        0            7                 1   
2           0         0         0        1            7                 2   
3           1         0         0        0            7                 3   
4           0         0         0        1            7                 3   
..        ...       ...       ...      ...          ...               ...   
695         1         0         0        0            5                 2   
696         1         0         0        0            5                 2   
697         1         0         0        0            5                 3   
698         0         0         0        1            5                 3   
699         0         0         0        1            5                 3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [27]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

In [28]:
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason4  Month Value  Date of the Week  \
0         0         0         0        1            7                 1   
1         0         0         0        0            7                 1   
2         0         0         0        1            7                 2   
3         1         0         0        0            7                 3   
4         0         0         0        1            7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

## データの標準化

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
absenteeism_scaler = StandardScaler()

In [54]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [57]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [58]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

# 訓練用、テスト用データへのデータの分割とシャッフル

## モジュールのインポート

In [59]:
from sklearn.model_selection import train_test_split

## 分割

In [60]:
train_test_split(scaled_inputs, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927, -0.58968976]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997,  1.12666297],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [61]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets)

In [62]:
x_train.shape

(525, 14)

In [63]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

## ロジスティック回帰

In [64]:
from sklearn.linear_model import LogisticRegression

### モデルの訓練

In [65]:
reg = LogisticRegression()

In [66]:
reg.fit(x_train, y_train)

C:\Users\unknow\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
reg.score(x_train, y_train)

0.7839285714285714

## 正解性の導出

In [68]:
model_outputs = reg.predict(x_train)

In [69]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [70]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [71]:
np.sum((model_outputs==y_train))/ model_outputs.shape[0]

0.7839285714285714

## 切片と係数

In [72]:
reg.intercept_

array([-0.21957576])

In [73]:
reg.coef_

array([[ 2.07452213,  0.33466331,  1.56097327,  1.32750188,  0.1878226 ,
        -0.07060017,  0.70649077, -0.03995965, -0.2009517 , -0.00462411,
         0.31937669, -0.13558227,  0.38168134, -0.33338757]])

In [74]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason4', 'Month Value',
       'Date of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [75]:
feature_name = unscaled_inputs.columns.values

In [76]:
summary_table = pd.DataFrame(columns=['Feature name'], data=feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.074522
1                  Reason_2     0.334663
2                  Reason_3     1.560973
3                   Reason4     1.327502
4               Month Value     0.187823
5          Date of the Week    -0.070600
6    Transportation Expense     0.706491
7          Distance to Work    -0.039960
8                       Age    -0.200952
9   Daily Work Load Average    -0.004624
10          Body Mass Index     0.319377
11                Education    -0.135582
12                 Children     0.381681
13                     Pets    -0.333388

In [77]:
summary_table.index = summary_table.index+1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.219576
1                  Reason_1     2.074522
2                  Reason_2     0.334663
3                  Reason_3     1.560973
4                   Reason4     1.327502
5               Month Value     0.187823
6          Date of the Week    -0.070600
7    Transportation Expense     0.706491
8          Distance to Work    -0.039960
9                       Age    -0.200952
10  Daily Work Load Average    -0.004624
11          Body Mass Index     0.319377
12                Education    -0.135582
13                 Children     0.381681
14                     Pets    -0.333388

# 係数の解釈

In [78]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [79]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.219576    0.802859
1                  Reason_1     2.074522    7.960741
2                  Reason_2     0.334663    1.397470
3                  Reason_3     1.560973    4.763455
4                   Reason4     1.327502    3.771610
5               Month Value     0.187823    1.206619
6          Date of the Week    -0.070600    0.931834
7    Transportation Expense     0.706491    2.026866
8          Distance to Work    -0.039960    0.960828
9                       Age    -0.200952    0.817952
10  Daily Work Load Average    -0.004624    0.995387
11          Body Mass Index     0.319377    1.376270
12                Education    -0.135582    0.873207
13                 Children     0.381681    1.464745
14                     Pets    -0.333388    0.716492

In [80]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.074522    7.960741
3                  Reason_3     1.560973    4.763455
4                   Reason4     1.327502    3.771610
7    Transportation Expense     0.706491    2.026866
13                 Children     0.381681    1.464745
2                  Reason_2     0.334663    1.397470
11          Body Mass Index     0.319377    1.376270
5               Month Value     0.187823    1.206619
10  Daily Work Load Average    -0.004624    0.995387
8          Distance to Work    -0.039960    0.960828
6          Date of the Week    -0.070600    0.931834
12                Education    -0.135582    0.873207
9                       Age    -0.200952    0.817952
0                 Intercept    -0.219576    0.802859
14                     Pets    -0.333388    0.716492

## モデルのテスト

In [91]:
reg.score(x_test, y_test)

0.7357142857142858

In [94]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.73825966, 0.26174034],
       [0.58795033, 0.41204967],
       [0.36712696, 0.63287304],
       [0.81162265, 0.18837735],
       [0.06127301, 0.93872699],
       [0.30690384, 0.69309616],
       [0.29493568, 0.70506432],
       [0.08079407, 0.91920593],
       [0.80400642, 0.19599358],
       [0.75999392, 0.24000608],
       [0.4622669 , 0.5377331 ],
       [0.15450706, 0.84549294],
       [0.04604734, 0.95395266],
       [0.72947484, 0.27052516],
       [0.23080142, 0.76919858],
       [0.55067175, 0.44932825],
       [0.52874769, 0.47125231],
       [0.55477826, 0.44522174],
       [0.38143834, 0.61856166],
       [0.0251927 , 0.9748073 ],
       [0.69578142, 0.30421858],
       [0.80421732, 0.19578268],
       [0.3768243 , 0.6231757 ],
       [0.39948746, 0.60051254],
       [0.18176149, 0.81823851],
       [0.75976147, 0.24023853],
       [0.46988997, 0.53011003],
       [0.88978022, 0.11021978],
       [0.13538822, 0.86461178],
       [0.79659382, 0.20340618],
       [0.

In [96]:
predicted_proba[:, 1]

array([0.26174034, 0.41204967, 0.63287304, 0.18837735, 0.93872699,
       0.69309616, 0.70506432, 0.91920593, 0.19599358, 0.24000608,
       0.5377331 , 0.84549294, 0.95395266, 0.27052516, 0.76919858,
       0.44932825, 0.47125231, 0.44522174, 0.61856166, 0.9748073 ,
       0.30421858, 0.19578268, 0.6231757 , 0.60051254, 0.81823851,
       0.24023853, 0.53011003, 0.11021978, 0.86461178, 0.20340618,
       0.38508703, 0.70505605, 0.70183345, 0.56406796, 0.19578268,
       0.54314403, 0.20541739, 0.82126457, 0.44520741, 0.61158096,
       0.2094607 , 0.40337164, 0.21409118, 0.09894294, 0.842517  ,
       0.66696405, 0.71725297, 0.27020317, 0.20195465, 0.1710223 ,
       0.57388094, 0.08343439, 0.67981314, 0.28675297, 0.87278627,
       0.48596026, 0.93274693, 0.24666308, 0.08214027, 0.08284243,
       0.7284407 , 0.67005252, 0.3124804 , 0.86066991, 0.18419083,
       0.26006746, 0.01324125, 0.22067156, 0.81294039, 0.31498837,
       0.20469486, 0.07167719, 0.93340874, 0.4637118 , 0.65566

## モデルの保存

In [97]:
import pickle

In [98]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [100]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)